
## This labels PRs based on branch name prefixes like feat/, fix/, etc.

feat:
  - head-branch: '^feat/.*'
fix:
  - head-branch: '^fix/.*'
chore:
  - head-branch: '^chore/.*'
ci:
  - head-branch: '^ci/.*'
